name: WakaTime Readme Stats

on:
  schedule:
    - cron: "*/30 * * * *" # Update every 30 minutes
  workflow_dispatch: # manual run
  push:
    branches: ["main", "master"]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: WakaTime Readme Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_PAT }}
          SECTION_NAME: waka

          SHOW_OS: True
          SHOW_PROJECTS: True
          SHOW_EDITORS: True
          SHOW_TIMEZONE: True
          SHOW_COMMIT: True
          SHOW_LANGUAGE: True
          SHOW_LINES_OF_CODE: False
          SHOW_LANGUAGE_PER_REPO: True
          SHOW_LOC_CHART: True
          SHOW_DAYS_OF_WEEK: True
          SHOW_PROFILE_VIEWS: True
          SHOW_SHORT_INFO: True
          SHOW_UPDATED_DATE: True
          SHOW_TOTAL_CODE_TIME: True

          COMMIT_BY_ME: False
          COMMIT_SINGLE: False
          COMMIT_MESSAGE: "Updated with Dev Metrics"

          LOCALE: en
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          SYMBOL_VERSION: 1
          DEBUG_LOGGING: true
