name: WakaTime Stats Update

on:
  schedule:
    - cron: "*/30 * * * *" # updates every 30 minutes
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update WakaTime Stats in README
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_UPDATED_DATE: "true"
          SHOW_TIMEZONE: "true"
          SHOW_PROJECTS: "true"
          SHOW_LANGUAGE: "true"
          SHOW_OS: "false"
          SHOW_COMMIT: "false"
